<?php
/**
 * @file
 * Creates an AJAX form using Drupal 7 Forms API
 * @link ajax AJAX Framework documentation @endlink and
 * @link http://drupal.org/node/752056 AJAX Forms handbook page @endlink.
 */

/**
 * Implements hook_menu().
 *
 * Sets up calls to drupal_get_form()
 */
function aeg_ajax_menu() {
  $items = array();

  $items['custom-modules'] = array(
    'title' => 'Custom modules',
    'page callback' => 'ajax_modules_intro',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  $items['custom-modules/ajax'] = array(
    'title' => 'AJAX custom',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_custom'),
    'access callback' => TRUE,
    'weight' => 0,
  );

  return $items;
}

/**
 * An introduction page for the aeg_ajax module
 */
function ajax_modules_intro() {
  $markup = t('This is an AJAX module that makes use of the Forms API');

  $list[] = l(t('AJAX Custom module'), 'custom-modules/ajax');

  $variables['items'] = $list;
  $variables['type'] = 'ul';
  $markup .= theme('item_list', $variables);

  return $markup;
}

/**
 * Simple form whose ajax-enabled 'changethis' member causes a text change
 * in the description of the 'replace_textfield' member.
 *
 * See @link http://drupal.org/node/262422 Form API Tutorial @endlink
 */
function ajax_custom($form, &$form_state) {
  $form = array();
  $form['changethis'] = array(
    '#title' => t("Choose something. Then, if you want to, tell us why!"),
    '#type' => 'select',
    '#options' => array(
      'one' => 'one',
      'two' => 'two',
      'three' => 'three',
    ),
    '#default_value' => 'one',
    '#ajax' => array(
      'callback' => 'aeg_ajax_callback',
      'wrapper' => 'replace_textfield_div',
      'effect' => 'slide',
      'progress' => array('type' => 'none'),
    ),
  );

  $form['tell_us_why'] = array(
    '#type' => 'radios',
    '#title' => t('Are you willing to tell us why?'),
    '#options' => array(
      0 => t('No'),
      1 => t('Yes'),
    ),
    '#default_value' => 0,
    '#required' => TRUE,
  );

  // This entire form element will be replaced whenever 'changethis' is updated.
  $form['replace_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t("State your reason"),
    // The prefix/suffix provide the div that we're replacing, named by
    // #ajax['wrapper'] above.
    '#prefix' => '<div id="replace_textfield_div">',
    '#suffix' => '</div>',
  );

  // An AJAX request calls the form builder function for every change.
  // We can change how we build the form based on $form_state.
  if (!empty($form_state['values']['changethis']) && $form_state['values']['tell_us_why'] == 1) {
    $form['replace_textfield']['#description'] = t("Say why you chose '@value'", array('@value' => $form_state['values']['changethis']));
  }
  else {
    $form['replace_textfield']['#title'] = t("Your reason is secret");
    $form['replace_textfield']['#type'] = "hidden";
  }

  return $form;
}

/**
 * Callback for ajax_custom.
 * @return array
 *   Renderable array (the textfield element)
 */
function aeg_ajax_callback($form, $form_state) {
  // The form has already been submitted and updated. We can return the replaced
  // item as it is.
  $element = $form['replace_textfield'];
  if (!empty($form_state['values']['tell_us_why']) && $form_state['values']['tell_us_why'] == 1) {
    $element['#value'] = "State your reason here";
  }
  else {
    $element['#value'] = "State your reason here";
  }
  return $element;
}
