<?php
/**
 * @file
 * Creates an AJAX form using Drupal 7 Forms API
 * @link ajax AJAX Framework documentation @endlink and
 * @link http://drupal.org/node/752056 AJAX Forms handbook page @endlink.
 */

/**
 * Implements hook_menu().
 *
 * Sets up calls to drupal_get_form()
 */
function aeg_ajax_menu() {
  $items = array();

  $items['custom-modules'] = array(
    'title' => 'Custom modules',
    'page callback' => 'ajax_modules_intro',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  $items['custom-modules/ajax'] = array(
    'title' => 'AJAX custom',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_custom'),
    'access callback' => TRUE,
    'weight' => 0,
  );

  return $items;
}

/**
 * An introduction page for the aeg_ajax module
 */
function ajax_modules_intro() {
  $markup = t('This is an AJAX module that makes use of the Forms API');

  $list[] = l(t('AJAX Custom module'), 'custom-modules/ajax');

  $variables['items'] = $list;
  $variables['type'] = 'ol';
  $markup .= theme('item_list', $variables);

  return $markup;
}

/**
 * Basic AJAX callback example.
 *
 * Simple form whose ajax-enabled 'changethis' member causes a text change
 * in the description of the 'replace_textfield' member.
 *
 * See @link http://drupal.org/node/262422 Form API Tutorial @endlink
 */
function ajax_custom($form, &$form_state) {
  $form = array();
  $form['changethis'] = array(
    '#title' => t("Choose something and explain why"),
    '#type' => 'select',
    '#options' => array(
      'one' => 'one',
      'two' => 'two',
      'three' => 'three',
    ),
    '#ajax' => array(
      // #ajax has two required keys: callback and wrapper.
      // 'callback' is a function that will be called when this element changes.
      'callback' => 'ajax_example_simplest_callback',
      // 'wrapper' is the HTML id of the page element that will be replaced.
      'wrapper' => 'replace_textfield_div',
      // There are also several optional keys - see ajax_example_autocheckboxes
      // below for details on 'method', 'effect' and 'speed' and
      // ajax_example_dependent_dropdown for 'event'.
    ),
  );

  // This entire form element will be replaced whenever 'changethis' is updated.
  $form['replace_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t("Why"),
    // The prefix/suffix provide the div that we're replacing, named by
    // #ajax['wrapper'] above.
    '#prefix' => '<div id="replace_textfield_div">',
    '#suffix' => '</div>',
  );

  // An AJAX request calls the form builder function for every change.
  // We can change how we build the form based on $form_state.
  if (!empty($form_state['values']['changethis'])) {
    $form['replace_textfield']['#description'] = t("Say why you chose '@value'", array('@value' => $form_state['values']['changethis']));
  }
  return $form;
}

/**
 * Callback for ajax_example_simplest.
 *
 * On an ajax submit, the form builder function is called again, then the $form
 * and $form_state are passed to this callback function so it can select which
 * portion of the form to send on to the client.
 *
 * @return array
 *   Renderable array (the textfield element)
 */
function aeg_ajax_simplest_callback($form, $form_state) {
  // The form has already been submitted and updated. We can return the replaced
  // item as it is.
  return $form['replace_textfield'];
}
